"""Universal Artifact SDK — native Python binding (``artifact-sdk/v1``).

Authoring API that emits the ``evaluable-artifact/v2`` submission format an evaluator
consumes. See ``SPEC.md`` for the contract and ``PYTHON_BINDING.md`` for the binding
design. Names are idiomatic ``snake_case``; serialized field names stay the schema's.

Quickstart::

    from universal_artifact_sdk import (
        Claim, Result, add_claim, add_result, create_artifact, write_submission,
    )

    artifact = create_artifact(id="expt-42", title="Feedback-driven contraction")
    add_claim(artifact, Claim(id="C1", statement="Feedback improves contraction"))
    add_result(artifact, Result(id="R1", validates=["C1"], evidence="out.csv", kind="metrics"))
    write_submission(artifact, "./out")

``__all__`` is the maintained public surface; ``python/tests/test_exports.py`` asserts it
against the TypeScript binding's exports.
"""

from .builder import (
    abandon_experiment,
    add_assessment,
    add_claim,
    add_dataset,
    add_environment,
    add_exhibit,
    add_experiment,
    add_result,
    add_trace,
    attach_paper,
    attach_research_agent,
    configure_journal,
    create_artifact,
    fail_experiment,
    get_assessment,
    get_claim,
    get_dataset,
    get_exhibit,
    get_experiment,
    get_result,
    get_trace,
    list_abandoned_experiments,
    list_assessments,
    list_claims,
    list_datasets,
    list_exhibits,
    list_experiments,
    list_journal,
    list_results,
    list_traces,
    purge_experiment,
    remove_assessment,
    remove_claim,
    remove_dataset,
    remove_exhibit,
    remove_experiment,
    remove_result,
    remove_trace,
    set_reflection,
    supersede_experiment,
)
from .inventory import EvidenceInventory, compute_evidence_inventory
from .model import (
    BUILTIN_CHECKS,
    CLAIM_STANCES,
    DEFAULT_CLAIM_STANCE,
    DISPOSITION_STATUSES,
    EXHIBIT_TYPES,
    FORMAT_VERSION,
    RESULT_KINDS,
    SDK_VERSION,
    TRACE_KINDS,
    VALIDATION_MODES,
    AddClaimInput,
    Artifact,
    Assessment,
    AttestValidator,
    BuiltinCheck,
    BuiltinValidator,
    ChangeContext,
    Claim,
    ClaimStance,
    Dataset,
    DatasetLocation,
    DataUse,
    Disposition,
    DispositionStatus,
    Environment,
    Exhibit,
    ExhibitType,
    Experiment,
    ExternalLocation,
    Failure,
    Hardware,
    Image,
    InArtifactLocation,
    InContainerLocation,
    InterRaterReliability,
    JournalConfig,
    JournalEntry,
    JournalOp,
    JournalTarget,
    LlmJudgeValidator,
    Locator,
    Paper,
    PaperReference,
    PendingChange,
    ProcedureTool,
    ProcedureValidator,
    QualitativeExcerpt,
    QualitativeSupport,
    RationalePolicy,
    ResearchAgent,
    Result,
    ResultKind,
    RunSpec,
    Sample,
    StudyMetadata,
    Trace,
    TraceKind,
    ValidationMode,
    Validator,
    artifact_from_dict,
    canonical_schema_path,
    default_exhibit_validation_mode,
    default_validation_mode,
    pinned_digest,
    to_dict,
    validator_from_dict,
)
from .open import open_submission, read_yaml
from .serialize import (
    GENERATED_MARKER,
    SubmissionReport,
    WriteOptions,
    write_submission,
    yaml_document,
)
from .validate import (
    GENERATED_RESERVED_PATHS,
    Issue,
    StructuralError,
    ValidationReport,
    validate_structure,
)

__all__ = [
    # constants and vocabularies
    "BUILTIN_CHECKS",
    "CLAIM_STANCES",
    "DEFAULT_CLAIM_STANCE",
    "DISPOSITION_STATUSES",
    "EXHIBIT_TYPES",
    "FORMAT_VERSION",
    "GENERATED_MARKER",
    "GENERATED_RESERVED_PATHS",
    "RESULT_KINDS",
    "SDK_VERSION",
    "TRACE_KINDS",
    "VALIDATION_MODES",
    # type aliases
    "BuiltinCheck",
    "ClaimStance",
    "DatasetLocation",
    "DispositionStatus",
    "ExhibitType",
    "JournalOp",
    "Locator",
    "RationalePolicy",
    "ResultKind",
    "TraceKind",
    "ValidationMode",
    "Validator",
    # models
    "AddClaimInput",
    "Artifact",
    "Assessment",
    "AttestValidator",
    "BuiltinValidator",
    "ChangeContext",
    "Claim",
    "DataUse",
    "Dataset",
    "Disposition",
    "Environment",
    "EvidenceInventory",
    "Exhibit",
    "Experiment",
    "ExternalLocation",
    "Failure",
    "Hardware",
    "Image",
    "InArtifactLocation",
    "InContainerLocation",
    "InterRaterReliability",
    "Issue",
    "JournalConfig",
    "JournalEntry",
    "JournalTarget",
    "LlmJudgeValidator",
    "Paper",
    "PaperReference",
    "PendingChange",
    "ProcedureTool",
    "ProcedureValidator",
    "QualitativeExcerpt",
    "QualitativeSupport",
    "ResearchAgent",
    "Result",
    "RunSpec",
    "Sample",
    "StructuralError",
    "StudyMetadata",
    "SubmissionReport",
    "Trace",
    "ValidationReport",
    "WriteOptions",
    # authoring
    "abandon_experiment",
    "add_assessment",
    "add_claim",
    "add_dataset",
    "add_environment",
    "add_exhibit",
    "add_experiment",
    "add_result",
    "add_trace",
    "attach_paper",
    "attach_research_agent",
    "configure_journal",
    "create_artifact",
    "fail_experiment",
    "get_assessment",
    "get_claim",
    "get_dataset",
    "get_exhibit",
    "get_experiment",
    "get_result",
    "get_trace",
    "list_abandoned_experiments",
    "list_assessments",
    "list_claims",
    "list_datasets",
    "list_exhibits",
    "list_experiments",
    "list_journal",
    "list_results",
    "list_traces",
    "purge_experiment",
    "remove_assessment",
    "remove_claim",
    "remove_dataset",
    "remove_exhibit",
    "remove_experiment",
    "remove_result",
    "remove_trace",
    "set_reflection",
    "supersede_experiment",
    # model helpers, validation, inventory, serialization, reopening
    "artifact_from_dict",
    "canonical_schema_path",
    "compute_evidence_inventory",
    "default_exhibit_validation_mode",
    "default_validation_mode",
    "open_submission",
    "pinned_digest",
    "read_yaml",
    "to_dict",
    "validate_structure",
    "validator_from_dict",
    "write_submission",
    "yaml_document",
]
